export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/**
 * EMPLOYERS
 */

export const REQUEST_EMPLOYERS = 'REQUEST_EMPLOYERS';
export const RECEIVE_EMPLOYERS = 'RECEIVE_EMPLOYERS';

/**
 * NOTIFICATION
 */

export const REQUEST_NOTIFICATION = 'REQUEST_EMPLOYERS';
export const RECEIVE_NOTIFICATION = 'RECEIVE_EMPLOYERS';

/**
 * ORGANIZATION
 */

export const REQUEST_ORGANIZATION = 'REQUEST_ORGANIZATION';
export const RECEIVE_ORGANIZATION = 'RECEIVE_ORGANIZATION';

/**
 * COURSES
 */

export const REQUEST_COURSES = 'REQUEST_COURSES';
export const RECEIVE_COURSES = 'RECEIVE_COURSES';
